name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'  # Daily

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 60 days and will be closed in 7 days if there is no further activity.'
          stale-pr-message: 'This PR has been inactive for 30 days and will be closed in 7 days if there is no further activity.'
          close-issue-message: 'This issue was closed due to inactivity. Feel free to reopen if needed.'
          close-pr-message: 'This PR was closed due to inactivity. Feel free to reopen if needed.'
          days-before-issue-stale: 60
          days-before-pr-stale: 30
          days-before-issue-close: 7
          days-before-pr-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,roadmap'
          exempt-pr-labels: 'pinned,security'
